---
- name: Установка Filebeat
  hosts: web
  become: yes
  gather_facts: true
  vars:
    kibana_host: "10.4.4.3:5601"
    elastic_host: "10.3.3.4:9200"

  tasks:
    - name: Установка зависимостей
      apt:
        name:
          - wget
          - curl
        state: present
        update_cache: yes
  
    - name: Загрузка filebeat с репозитория
      shell: wget https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-7.17.15-amd64.deb
      args:
        chdir: /tmp

    - name: Установка filebeat
      shell: dpkg -i filebeat-7.17.15-amd64.deb
      args:
        chdir: /tmp

    - name: Копируем конфиг filebeat
      template:
        src: ./templates/filebeat.j2
        dest: /etc/filebeat/filebeat.yml

    - name: daemon_reload
      systemd:
        daemon_reload: true
        
    - name: Перезапускаем filebeat и добавляем в автозагрузку
      service:
        name: filebeat
        state: restarted
        enabled: yes
