---
- name: Установка Kibana
  hosts: kibana_srv
  become: yes
  vars:
    elastic_httphost: "10.3.3.4:9200"
    kibana_version: "7.15.1"

  tasks:

    - name: Установка зависимостей
      apt:
        name:
          - wget
          - curl
        state: present
        update_cache: yes
  
    - name: Загрузка filebeat с репозитория
      shell: wget https://mirror.yandex.ru/mirrors/elastic/7/pool/main/k/kibana/kibana-7.17.15-amd64.deb
      args:
        chdir: /tmp

    - name: Установка filebeat
      shell: dpkg -i kibana-7.17.15-amd64.deb
      args:
        chdir: /tmp

    - name: Копируем конфигурационный файл kibana
      template:
        src: ./templates/kibana.j2
        dest: /etc/kibana/kibana.yml

    - name: daemon_reload
      systemd:
        daemon_reload: true

    - name:  Перезапускаем kibana и добавляем в автозагрузку
      service:
        name: kibana
        state: restarted
        enabled: yes
